### ISSUE TITLE
discoveryd

### ISSUE THREAD

**Issue by florianschommertz** [jdachtera/node-rtpmidi#10]
Hi Jdachtera,

is there a chance that this will be still developed in the future? - Anything regarding "discoveryd" instead of "mdns"? - I'd like to get this up n running from with a Phonegap Application but I'm stuck on "mDNS discovery is not available." already on Yosemite Terminal.

All the best
florian

**Comment by jdachtera** [comment]
Right now I have no plans to work on this since I don't really have a use for it at the moment. That said I'm of course open for contributions :)

It would be possible to implement an alternative mdns implementation. If you look at https://github.com/jdachtera/node-rtpmidi/blob/master/src/mdns/ there is even one using some webos services. Also the mdns discovery shouldn't be necessary for the library to work if you supply the ip address information manually.

To get it working in cordova/phonegap you will need an emulation of the node.js dgram api. Maybe  https://github.com/andischerer/cordova-plugin-dgram could work? 

Best
Jascha

**Comment by florianschommertz** [comment]
Hi Jascha,

I'm trying to get my head around this. With your code it ooks so easy at first. :D

thank you for the links
all the best — florian
